spatial_name: MERFISH
scrna_name: Moffit
magic: magic

spatial_file: ./data/MERFISH_extract0.csv.pkl
scrna_file: ./data/Moffit_magic.txt.pkl
loc_file: ./data/MERFISH_extract0_Locations.csv
neighbor_file: ./data/w_{0}_{1}_{2}_fold{3}.pkl

train:
  name: train
  lr: 0.00004
  max_epoch_num: 30
  lasso_weight: 0.1
  spot_weight: 0.1
  t_min: 3
  stop_loss: 0.2
  batch_size: 512
  top_k: 2000

pred:
  n_neighbors: 50
