spatial_name: osmFISH
scrna_name: Allen
magic: norm

spatial_file: ./data/osmFISH_Cortex_scvi_norm.csv.pkl
scrna_file: ./data/Allen_SSp_norm.txt.pkl
loc_file: ./data/osm_Locations.txt
neighbor_file: /home/wangwk/singlecell/ST_RNA/Lasso/model/w_{0}_{1}_{2}_fold{3}.pkl

train:
  name: train
  lr: 0.0015
  max_epoch_num: 30
  lasso_weight: 0.1
  spot_weight: 0.1
  t_min: 3
  stop_loss: 0.2
  batch_size: 512
  top_k: 2000

pred:
  n_neighbors: 50
