spatial_name: STARmap
scrna_name: AllenVISp
magic: magic

spatial_file: ./data/STARmap_norm.csv.pkl
scrna_file: ./data/AllenVISp_magic.csv.pkl
loc_file: ./data/STAR_Locations.tsv
neighbor_file: ./data/w_{0}_{1}_{2}_fold{3}.pkl

train:
  name: train
  lr: 0.0005
  max_epoch_num: 30
  lasso_weight: 0.1
  spot_weight: 0.1
  t_min: 3
  stop_loss: 0.2
  batch_size: 512
  top_k: 2000

pred:
  n_neighbors: 50
